"""
Reference data constants for Histacruise.
Imported by both seed.py and app.py startup auto-seeder.
No Flask/SQLAlchemy imports here to avoid circular dependencies.
"""

CRUISE_LINES = [
    'Royal Caribbean', 'Carnival Cruise Line', 'Norwegian Cruise Line',
    'Celebrity Cruises', 'Disney Cruise Line', 'MSC Cruises',
    'Princess Cruises', 'Holland America Line', 'Costa Cruises',
    'AIDA Cruises', 'Virgin Voyages', 'Cunard', 'Oceania Cruises',
    'Azamara', 'Regent Seven Seas Cruises', 'Silversea Cruises',
    'Viking Ocean Cruises', 'Seabourn', 'P&O Cruises',
]

SHIPS = {
    'Royal Caribbean': [
        'Wonder of the Seas', 'Symphony of the Seas', 'Harmony of the Seas',
        'Allure of the Seas', 'Oasis of the Seas', 'Icon of the Seas',
        'Odyssey of the Seas', 'Quantum of the Seas', 'Anthem of the Seas',
        'Ovation of the Seas', 'Navigator of the Seas', 'Mariner of the Seas',
        'Explorer of the Seas', 'Adventure of the Seas', 'Freedom of the Seas',
        'Liberty of the Seas', 'Independence of the Seas', 'Brilliance of the Seas',
        'Serenade of the Seas', 'Jewel of the Seas', 'Enchantment of the Seas',
        'Vision of the Seas', 'Sovereign of the Seas',
    ],
    'Carnival Cruise Line': [
        'Mardi Gras', 'Carnival Celebration', 'Carnival Jubilee',
        'Carnival Horizon', 'Carnival Vista', 'Carnival Panorama',
        'Carnival Sunshine', 'Carnival Sunrise', 'Carnival Magic',
        'Carnival Breeze', 'Carnival Dream', 'Carnival Freedom',
        'Carnival Liberty', 'Carnival Valor', 'Carnival Conquest',
        'Carnival Glory', 'Carnival Miracle', 'Carnival Legend',
        'Carnival Pride', 'Carnival Spirit', 'Carnival Elation',
        'Carnival Paradise',
    ],
    'Norwegian Cruise Line': [
        'Norwegian Prima', 'Norwegian Viva', 'Norwegian Escape',
        'Norwegian Bliss', 'Norwegian Encore', 'Norwegian Joy',
        'Norwegian Breakaway', 'Norwegian Getaway', 'Norwegian Epic',
        'Norwegian Pearl', 'Norwegian Jade', 'Norwegian Gem',
        'Norwegian Dawn', 'Norwegian Star', 'Norwegian Sun',
        'Norwegian Sky', 'Norwegian Spirit',
    ],
    'Celebrity Cruises': [
        'Celebrity Ascent', 'Celebrity Beyond', 'Celebrity Apex',
        'Celebrity Edge', 'Celebrity Reflection', 'Celebrity Silhouette',
        'Celebrity Equinox', 'Celebrity Eclipse', 'Celebrity Solstice',
        'Celebrity Constellation', 'Celebrity Summit', 'Celebrity Millennium',
        'Celebrity Infinity', 'Celebrity Xcel',
    ],
    'Disney Cruise Line': [
        'Disney Wish', 'Disney Dream', 'Disney Fantasy',
        'Disney Magic', 'Disney Wonder', 'Disney Treasure',
    ],
    'MSC Cruises': [
        'MSC World Europa', 'MSC Seashore', 'MSC Seascape',
        'MSC Virtuosa', 'MSC Grandiosa', 'MSC Bellissima',
        'MSC Meraviglia', 'MSC Seaview', 'MSC Seaside',
        'MSC Preziosa', 'MSC Divina', 'MSC Splendida',
        'MSC Fantasia', 'MSC Musica', 'MSC Orchestra',
        'MSC Magnifica',
    ],
    'Princess Cruises': [
        'Sun Princess', 'Star Princess', 'Discovery Princess',
        'Enchanted Princess', 'Sky Princess', 'Majestic Princess',
        'Regal Princess', 'Royal Princess', 'Caribbean Princess',
        'Crown Princess', 'Emerald Princess', 'Ruby Princess',
        'Sapphire Princess', 'Diamond Princess', 'Coral Princess',
        'Island Princess',
    ],
    'Holland America Line': [
        'Rotterdam', 'Nieuw Statendam', 'Koningsdam',
        'Oosterdam', 'Westerdam', 'Noordam',
        'Zuiderdam', 'Eurodam', 'Nieuw Amsterdam',
        'Volendam', 'Zaandam',
    ],
    'Costa Cruises': [
        'Costa Toscana', 'Costa Firenze', 'Costa Smeralda',
        'Costa Luminosa', 'Costa Deliziosa', 'Costa Fascinosa',
        'Costa Favolosa', 'Costa Diadema', 'Costa Pacifica',
        'Costa Serena', 'Costa Magica', 'Costa Fortuna',
    ],
    'AIDA Cruises': [
        'AIDAnova', 'AIDAcosma', 'AIDAprima', 'AIDAperla',
        'AIDAbella', 'AIDAluna', 'AIDAmar', 'AIDAstella',
        'AIDAsol', 'AIDAdiva', 'AIDAaura', 'AIDAvita',
    ],
    'Virgin Voyages': [
        'Scarlet Lady', 'Valiant Lady', 'Resilient Lady', 'Brilliant Lady',
    ],
    'Cunard': [
        'Queen Mary 2', 'Queen Victoria', 'Queen Elizabeth', 'Queen Anne',
    ],
    'Oceania Cruises': [
        'Vista', 'Riviera', 'Marina', 'Insignia',
        'Nautica', 'Regatta', 'Sirena',
    ],
    'Azamara': [
        'Azamara Quest', 'Azamara Journey', 'Azamara Pursuit',
        'Azamara Onward',
    ],
    'Regent Seven Seas Cruises': [
        'Seven Seas Grandeur', 'Seven Seas Splendor', 'Seven Seas Explorer',
        'Seven Seas Voyager', 'Seven Seas Navigator', 'Seven Seas Mariner',
    ],
    'Silversea Cruises': [
        'Silver Nova', 'Silver Dawn', 'Silver Moon', 'Silver Origin',
        'Silver Muse', 'Silver Spirit', 'Silver Shadow', 'Silver Whisper',
        'Silver Wind', 'Silver Cloud',
    ],
    'Viking Ocean Cruises': [
        'Viking Jupiter', 'Viking Saturn', 'Viking Neptune', 'Viking Mars',
        'Viking Venus', 'Viking Orion', 'Viking Sky', 'Viking Sea',
        'Viking Star',
    ],
    'Seabourn': [
        'Seabourn Pursuit', 'Seabourn Venture', 'Seabourn Encore',
        'Seabourn Ovation', 'Seabourn Odyssey', 'Seabourn Sojourn',
        'Seabourn Quest',
    ],
    'P&O Cruises': [
        'Iona', 'Arvia', 'Britannia', 'Aurora', 'Arcadia', 'Ventura', 'Azura',
    ],
}

REGIONS = [
    'Caribbean', 'Mediterranean', 'Alaska', 'Bahamas',
    'Northern Europe', 'Mexico', 'Hawaii', 'Bermuda',
    'South America', 'Asia', 'Australia & New Zealand',
    'Transatlantic', 'Canary Islands', 'British Isles',
    'Indian Ocean', 'Middle East', 'Africa',
]

# (name, city, country, latitude, longitude)
PORTS = [
    # United States
    ('Port of Miami',              'Miami',           'United States',  25.7742,  -80.1747),
    ('Port Everglades',            'Fort Lauderdale', 'United States',  26.0979,  -80.1150),
    ('Port Canaveral',             'Cape Canaveral',  'United States',  28.4158,  -80.5917),
    ('Port of Tampa',              'Tampa',           'United States',  27.9290,  -82.4459),
    ('Port of New Orleans',        'New Orleans',     'United States',  29.9457,  -90.0615),
    ('Port of Galveston',          'Galveston',       'United States',  29.3013,  -94.7977),
    ('Port of Baltimore',          'Baltimore',       'United States',  39.2604,  -76.5788),
    ('Port of New York',           'New York',        'United States',  40.6892,  -74.0445),
    ('Port of Seattle',            'Seattle',         'United States',  47.6062, -122.3321),
    ('Port of San Francisco',      'San Francisco',   'United States',  37.8044, -122.4730),
    ('Port of Los Angeles',        'Los Angeles',     'United States',  33.7394, -118.2630),
    ('Port of San Diego',          'San Diego',       'United States',  32.7157, -117.1611),
    ('Juneau Cruise Terminal',     'Juneau',          'United States',  58.3005, -134.4197),
    ('Skagway Cruise Terminal',    'Skagway',         'United States',  59.4583, -135.3139),
    ('Ketchikan Cruise Terminal',  'Ketchikan',       'United States',  55.3422, -131.6461),
    ('Sitka Cruise Terminal',      'Sitka',           'United States',  57.0531, -135.3300),
    ('Seward Cruise Terminal',     'Seward',          'United States',  60.1041, -149.4428),
    ('Whittier Cruise Terminal',   'Whittier',        'United States',  60.7738, -148.6838),
    ('Honolulu Cruise Terminal',   'Honolulu',        'United States',  21.3069, -157.8583),
    ('Kahului Harbor',             'Kahului',         'United States',  20.8893, -156.4729),
    ('Nawiliwili Harbor',          'Lihue',           'United States',  21.9511, -159.3556),
    ('Hilo Harbor',                'Hilo',            'United States',  19.7297, -155.0900),
    # Bahamas
    ('Nassau Cruise Port',         'Nassau',          'Bahamas',        25.0833,  -77.3500),
    ('Freeport Cruise Port',       'Freeport',        'Bahamas',        26.5285,  -78.6956),
    ('Perfect Day at CocoCay',     'CocoCay',         'Bahamas',        25.8233,  -77.8308),
    ('Half Moon Cay',              'Half Moon Cay',   'Bahamas',        25.0658,  -77.3825),
    ('Princess Cays',              'Eleuthera',       'Bahamas',        25.1280,  -76.1490),
    ('Labadee',                    'Labadee',         'Haiti',          19.7500,  -73.0167),
    ('Great Stirrup Cay',          'Great Stirrup Cay','Bahamas',       25.8333,  -77.9000),
    ('Ocean Cay MSC Marine Reserve','Ocean Cay',      'Bahamas',        25.3667,  -79.0833),
    ('Castaway Cay',               'Castaway Cay',    'Bahamas',        26.0167,  -77.5333),
    ('Lookout Cay at Lighthouse Point','Eleuthera',   'Bahamas',        25.2500,  -76.3333),
    ('Celebration Key',            'Grand Bahama',    'Bahamas',        26.5000,  -78.7000),
    ('Beach Club at Bimini',       'Bimini',          'Bahamas',        25.7281,  -79.2981),
    # Mexico
    ('Cozumel Pier',               'Cozumel',         'Mexico',         20.5088,  -86.9517),
    ('Ensenada Cruise Terminal',   'Ensenada',        'Mexico',         31.8676, -116.5961),
    ('Puerto Vallarta',            'Puerto Vallarta',  'Mexico',        20.6534, -105.2253),
    ('Cabo San Lucas',             'Cabo San Lucas',  'Mexico',         22.8905, -109.9167),
    ('Mazatlan',                   'Mazatlan',        'Mexico',         23.2494, -106.4111),
    ('Manzanillo',                 'Manzanillo',      'Mexico',         19.0522, -104.3190),
    ('Costa Maya',                 'Mahahual',        'Mexico',         18.7130,  -87.7040),
    ('Progreso',                   'Progreso',        'Mexico',         21.2833,  -89.6667),
    # Caribbean
    ('St. Thomas WICO',            'Charlotte Amalie','US Virgin Islands',18.3381,-64.9307),
    ('Frederiksted Pier',          'Frederiksted',    'US Virgin Islands',17.7133,-64.8811),
    ('San Juan Cruise Terminal',   'San Juan',        'Puerto Rico',    18.4655,  -66.1057),
    ('Grand Cayman Cruise Terminal','George Town',    'Cayman Islands', 19.2869,  -81.3674),
    ('Falmouth Cruise Terminal',   'Falmouth',        'Jamaica',        18.4942,  -77.6560),
    ('Ocho Rios Cruise Terminal',  'Ocho Rios',       'Jamaica',        18.4082,  -77.1040),
    ('Montego Bay Cruise Port',    'Montego Bay',     'Jamaica',        18.4678,  -77.9128),
    ('Philipsburg Cruise Terminal','Philipsburg',     'Sint Maarten',   18.0278,  -63.0444),
    ('Oranjestad Cruise Port',     'Oranjestad',      'Aruba',          12.5246,  -70.0273),
    ('Willemstad Cruise Terminal', 'Willemstad',      'Curacao',        12.1084,  -68.9335),
    ('Bridgetown Cruise Terminal', 'Bridgetown',      'Barbados',       13.1132,  -59.6199),
    ('Castries Cruise Terminal',   'Castries',        'St. Lucia',      14.0101,  -60.9872),
    ('Basseterre Cruise Port',     'Basseterre',      'St. Kitts',      17.2983,  -62.7271),
    ('Roseau Cruise Terminal',     'Roseau',          'Dominica',       15.3017,  -61.3878),
    ('Gustavia Cruise Terminal',   'Gustavia',        'St. Barthelemy', 17.8964,  -62.8520),
    ('Pointe-a-Pitre',             'Pointe-a-Pitre',  'Guadeloupe',     16.2350,  -61.5344),
    ('Fort-de-France',             'Fort-de-France',  'Martinique',     14.6037,  -61.0735),
    ('Belize City Cruise Terminal','Belize City',     'Belize',         17.2510,  -88.7590),
    ('Roatan Cruise Terminal',     'Coxen Hole',      'Honduras',       16.3178,  -86.5358),
    ('Puerto Cortes',              'Puerto Cortes',   'Honduras',       15.8500,  -87.9333),
    # Bermuda
    ('Kings Wharf',                'Sandys Parish',   'Bermuda',        32.3078,  -64.8290),
    # Canada
    ('Port of Vancouver',          'Vancouver',       'Canada',         49.2827, -123.1207),
    ('Port of Quebec',             'Quebec City',     'Canada',         46.8139,  -71.2080),
    ('Halifax Cruise Terminal',    'Halifax',         'Canada',         44.6488,  -63.5752),
    # Mediterranean
    ('Barcelona Cruise Port',      'Barcelona',       'Spain',          41.3614,    2.1731),
    ('Valencia Cruise Terminal',   'Valencia',        'Spain',          39.4699,   -0.3774),
    ('Malaga Cruise Port',         'Malaga',          'Spain',          36.7213,   -4.4214),
    ('Palma de Mallorca Port',     'Palma',           'Spain',          39.5696,    2.6502),
    ('Cadiz Cruise Terminal',      'Cadiz',           'Spain',          36.5271,   -6.2886),
    ('Civitavecchia Port',         'Rome',            'Italy',          42.0941,   11.7962),
    ('Venice Cruise Terminal',     'Venice',          'Italy',          45.4408,   12.3155),
    ('Naples Cruise Terminal',     'Naples',          'Italy',          40.8358,   14.2488),
    ('Livorno Cruise Terminal',    'Livorno',         'Italy',          43.5481,   10.3116),
    ('Genoa Cruise Terminal',      'Genoa',           'Italy',          44.4056,    8.9463),
    ('Messina Cruise Terminal',    'Messina',         'Italy',          38.1938,   15.5540),
    ('Palermo Cruise Terminal',    'Palermo',         'Italy',          38.1157,   13.3615),
    ('Cagliari Cruise Terminal',   'Cagliari',        'Italy',          39.2238,    9.1217),
    ('Marseille Cruise Terminal',  'Marseille',       'France',         43.2965,    5.3698),
    ('Monaco Cruise Terminal',     'Monaco',          'Monaco',         43.7384,    7.4246),
    ('Cannes Cruise Anchorage',    'Cannes',          'France',         43.5528,    7.0174),
    ('Piraeus Cruise Terminal',    'Athens',          'Greece',         37.9480,   23.6441),
    ('Santorini Cruise Anchorage', 'Fira',            'Greece',         36.4167,   25.4333),
    ('Mykonos Cruise Anchorage',   'Mykonos Town',    'Greece',         37.4467,   25.3289),
    ('Heraklion Cruise Port',      'Heraklion',       'Greece',         35.3387,   25.1442),
    ('Rhodes Cruise Terminal',     'Rhodes',          'Greece',         36.4349,   28.2176),
    ('Corfu Cruise Terminal',      'Corfu',           'Greece',         39.6243,   19.9217),
    ('Kotor Cruise Port',          'Kotor',           'Montenegro',     42.4247,   18.7712),
    ('Dubrovnik Cruise Port',      'Dubrovnik',       'Croatia',        42.6507,   18.0944),
    ('Split Cruise Terminal',      'Split',           'Croatia',        43.5081,   16.4402),
    ('Valletta Cruise Port',       'Valletta',        'Malta',          35.9042,   14.5189),
    ('Istanbul Cruise Terminal',   'Istanbul',        'Turkey',         41.0082,   28.9784),
    ('Kusadasi Cruise Port',       'Kusadasi',        'Turkey',         37.8586,   27.2594),
    ('Lisbon Cruise Terminal',     'Lisbon',          'Portugal',       38.7223,   -9.1393),
    ('Gibraltar Cruise Terminal',  'Gibraltar',       'Gibraltar',      36.1408,   -5.3536),
    # Northern Europe
    ('Southampton Cruise Terminal','Southampton',     'United Kingdom', 50.9097,   -1.4044),
    ('Dover Cruise Terminal',      'Dover',           'United Kingdom', 51.1279,    1.3134),
    ('Edinburgh (Leith)',          'Edinburgh',       'United Kingdom', 55.9533,   -3.1883),
    ('Liverpool Cruise Terminal',  'Liverpool',       'United Kingdom', 53.4084,   -2.9916),
    ('Amsterdam Cruise Terminal',  'Amsterdam',       'Netherlands',    52.3676,    4.9041),
    ('Zeebrugge Cruise Port',      'Bruges',          'Belgium',        51.3333,    3.2000),
    ('Hamburg Cruise Terminal',    'Hamburg',         'Germany',        53.5753,    9.9675),
    ('Copenhagen Cruise Terminal', 'Copenhagen',      'Denmark',        55.6761,   12.5683),
    ('Stockholm Cruise Terminal',  'Stockholm',       'Sweden',         59.3293,   18.0686),
    ('Helsinki Cruise Terminal',   'Helsinki',        'Finland',        60.1699,   24.9384),
    ('Tallinn Cruise Terminal',    'Tallinn',         'Estonia',        59.4370,   24.7536),
    ('Riga Cruise Terminal',       'Riga',            'Latvia',         56.9460,   24.1059),
    ('Oslo Cruise Terminal',       'Oslo',            'Norway',         59.9139,   10.7522),
    ('Bergen Cruise Terminal',     'Bergen',          'Norway',         60.3913,    5.3221),
    ('Stavanger Cruise Terminal',  'Stavanger',       'Norway',         58.9700,    5.7331),
    ('Reykjavik Cruise Terminal',  'Reykjavik',       'Iceland',        64.1355,  -21.8954),
    ('St. Petersburg Cruise Terminal','St. Petersburg','Russia',        59.9343,   30.3351),
    # South America
    ('Buenos Aires Cruise Terminal','Buenos Aires',   'Argentina',     -34.6037,  -58.3816),
    ('Montevideo Cruise Terminal', 'Montevideo',      'Uruguay',       -34.9011,  -56.1645),
    ('Rio de Janeiro Cruise Port', 'Rio de Janeiro',  'Brazil',        -22.9068,  -43.1729),
    ('Santos Cruise Terminal',     'Santos',          'Brazil',        -23.9608,  -46.3336),
    ('Cartagena Cruise Terminal',  'Cartagena',       'Colombia',        10.3910,  -75.4794),
    ('Colon Cruise Terminal',      'Colon',           'Panama',           9.3547,  -79.9006),
    ('Valparaiso Cruise Terminal', 'Valparaiso',      'Chile',          -33.0472,  -71.6127),
    # Asia
    ('Singapore Cruise Centre',    'Singapore',       'Singapore',        1.2566,  103.8198),
    ('Yokohama Cruise Terminal',   'Yokohama',        'Japan',           35.4437,  139.6380),
    ('Kobe Cruise Terminal',       'Kobe',            'Japan',           34.6901,  135.1956),
    ('Osaka Cruise Terminal',      'Osaka',           'Japan',           34.6937,  135.5023),
    ('Nagasaki Cruise Terminal',   'Nagasaki',        'Japan',           32.7503,  129.8777),
    ('Hong Kong Cruise Terminal',  'Hong Kong',       'Hong Kong',       22.3193,  114.1694),
    ('Shanghai Cruise Terminal',   'Shanghai',        'China',           31.2304,  121.4737),
    ('Tianjin Cruise Terminal',    'Tianjin',         'China',           38.9973,  117.7383),
    ('Busan Cruise Terminal',      'Busan',           'South Korea',     35.1796,  129.0756),
    ('Laem Chabang Cruise Terminal','Bangkok',        'Thailand',        13.0827,  100.8807),
    ('Ho Chi Minh City Port',      'Ho Chi Minh City','Vietnam',         10.8231,  106.6297),
    ('Da Nang Cruise Terminal',    'Da Nang',         'Vietnam',         16.0544,  108.2022),
    ('Bali Cruise Terminal',       'Benoa',           'Indonesia',       -8.7500,  115.2167),
    # Australia & New Zealand
    ('Sydney Overseas Passenger Terminal','Sydney',   'Australia',      -33.8688,  151.2093),
    ('Melbourne Cruise Terminal',  'Melbourne',       'Australia',      -37.8136,  144.9631),
    ('Brisbane Cruise Terminal',   'Brisbane',        'Australia',      -27.4698,  153.0251),
    ('Fremantle Cruise Terminal',  'Fremantle',       'Australia',      -32.0569,  115.7439),
    ('Auckland Cruise Terminal',   'Auckland',        'New Zealand',    -36.8485,  174.7633),
    ('Wellington Cruise Terminal', 'Wellington',      'New Zealand',    -41.2865,  174.7762),
    # Canary Islands
    ('Las Palmas Cruise Port',     'Las Palmas',      'Spain',           28.1248,  -15.4300),
    ('Santa Cruz de Tenerife',     'Santa Cruz',      'Spain',           28.4636,  -16.2518),
    ('Arrecife Cruise Port',       'Lanzarote',       'Spain',           28.9637,  -13.5481),
    # Middle East
    ('Dubai Cruise Terminal',      'Dubai',           'UAE',             25.2048,   55.2708),
    ('Abu Dhabi Cruise Terminal',  'Abu Dhabi',       'UAE',             24.4539,   54.3773),
    ('Aqaba Cruise Terminal',      'Aqaba',           'Jordan',          29.5269,   35.0060),
    # Africa
    ('Cape Town Cruise Terminal',  'Cape Town',       'South Africa',   -33.9249,   18.4241),
    ('Mombasa Cruise Terminal',    'Mombasa',         'Kenya',           -4.0435,   39.6682),
    ('Port Louis Cruise Terminal', 'Port Louis',      'Mauritius',      -20.1609,   57.4989),

    # ---- Additional ports from gangwaze.com world cruise port list ----

    # Alaska (additional)
    ('Anchorage Cruise Dock',              'Anchorage',             'United States',   61.2181, -149.9003),
    ('Haines Cruise Dock',                 'Haines',                'United States',   59.2358, -135.4453),
    ('Icy Strait Point',                   'Hoonah',                'United States',   58.1097, -135.4417),

    # Bermuda (additional)
    ('Hamilton Cruise Port',               'Hamilton',              'Bermuda',         32.2942,  -64.7839),

    # Canada / New England (additional)
    ('Bar Harbor Pier',                    'Bar Harbor',            'United States',   44.3876,  -68.2039),
    ('Boston Black Falcon Cruise Terminal','Boston',                'United States',   42.3601,  -71.0589),
    ('Charlottetown Cruise Dock',          'Charlottetown',         'Canada',          46.2382,  -63.1311),
    ('Montreal Cruise Terminal',           'Montreal',              'Canada',          45.5017,  -73.5673),
    ('Saint John Cruise Terminal',         'Saint John',            'Canada',          45.2733,  -66.0633),
    ('Sydney NS Cruise Dock',              'Sydney',                'Canada',          46.1368,  -60.1942),

    # Caribbean (additional)
    ('Amber Cove Cruise Center',           'Puerto Plata',          'Dominican Republic', 19.8003, -70.7003),
    ('Grand Turk Cruise Center',           'Cockburn Town',         'Turks and Caicos Islands', 21.4667, -71.1417),
    ('Harvest Caye',                       'Placencia',             'Belize',          16.4958,  -88.3636),
    ('Kralendijk Cruise Port',             'Kralendijk',            'Bonaire',         12.1453,  -68.2756),
    ('La Romana Cruise Port',              'La Romana',             'Dominican Republic', 18.4096, -68.9724),
    ('Mahogany Bay Cruise Port',           'Roatan',                'Honduras',        16.3500,  -86.7667),
    ('Marigot Cruise Dock',                'Marigot',               'Saint Martin',    18.0708,  -63.0825),
    ('Punta Cana Cruise Port',             'La Altagracia',         'Dominican Republic', 18.5601, -68.3725),
    ('Road Town Cruise Pier',              'Road Town',             'British Virgin Islands', 18.4167, -64.6167),
    ('Samana Cruise Port',                 'Samana',                'Dominican Republic', 19.2061, -69.3364),
    ("St. George's Cruise Terminal",       "St. George's",          'Grenada',         12.0561,  -61.7486),
    ("St. John's Heritage Quay",           "St. John's",            'Antigua',         17.1175,  -61.8456),
    ('Jost Van Dyke Anchorage',            'Great Harbour',         'British Virgin Islands', 18.4433, -64.7497),

    # Europe / Mediterranean (additional)
    ('Aarhus Cruise Terminal',             'Aarhus',                'Denmark',         56.1629,   10.2039),
    ('Aghios Nikolaos Anchorage',          'Aghios Nikolaos',       'Greece',          35.1900,   25.7100),
    ('Akureyri Cruise Dock',               'Akureyri',              'Iceland',         65.6835,  -18.0878),
    ('Alesund Cruise Quay',                'Alesund',               'Norway',          62.4722,    6.1549),
    ('Alexandria Cruise Terminal',         'Alexandria',            'Egypt',           31.2001,   29.9187),
    ('Amalfi Tender Port',                 'Amalfi',                'Italy',           40.6340,   14.6027),
    ('Argostoli Cruise Dock',              'Argostoli',             'Greece',          38.1753,   20.4878),
    ('Bari Cruise Terminal',               'Bari',                  'Italy',           41.1171,   16.8719),
    ('Belfast Cruise Terminal',            'Belfast',               'United Kingdom',  54.6079,   -5.9264),
    ('Bodrum Cruise Port',                 'Bodrum',                'Turkey',          37.0342,   27.4305),
    ('Bordeaux Cruise Terminal',           'Bordeaux',              'France',          44.8378,   -0.5792),
    ('Bratislava River Cruise Terminal',   'Bratislava',            'Slovakia',        48.1486,   17.1077),
    ('Budapest River Cruise Terminal',     'Budapest',              'Hungary',         47.4979,   19.0402),
    ('Capri Marina Grande',                'Capri',                 'Italy',           40.5508,   14.2428),
    ('Cartagena Spain Cruise Terminal',    'Cartagena',             'Spain',           37.6057,   -0.9841),
    ('Catania Cruise Terminal',            'Catania',               'Italy',           37.5079,   15.0830),
    ('Cork Cruise Terminal',               'Cork',                  'Ireland',         51.8985,   -8.4756),
    ('Dresden River Port',                 'Dresden',               'Germany',         51.0504,   13.7373),
    ('Dublin Cruise Terminal',             'Dublin',                'Ireland',         53.3498,   -6.2603),
    ('Falmouth England Cruise Port',       'Falmouth',              'United Kingdom',  50.1526,   -5.0668),
    ('Funchal Cruise Terminal',            'Funchal',               'Portugal',        32.6500,  -16.9167),
    ('Geiranger Tender Port',              'Geiranger',             'Norway',          62.1006,    7.2051),
    ('Glasgow Cruise Terminal',            'Glasgow',               'United Kingdom',  55.8642,   -4.2518),
    ('Harwich International Port',         'Harwich',               'United Kingdom',  51.9442,    1.2611),
    ('Honningsvag Cruise Dock',            'Honningsvag',           'Norway',          70.9822,   25.9729),
    ('Ijmuiden Cruise Terminal',           'Ijmuiden',              'Netherlands',     52.4617,    4.5961),
    ('Invergordon Cruise Terminal',        'Invergordon',           'United Kingdom',  57.6893,   -4.1679),
    ('Inverness Cruise Terminal',          'Inverness',             'United Kingdom',  57.4778,   -4.2247),
    ('Katakolon Cruise Port',              'Katakolon',             'Greece',          37.6497,   21.3208),
    ('Kiel Cruise Terminal',               'Kiel',                  'Germany',         54.3233,   10.1228),
    ('Koblenz River Cruise Terminal',      'Koblenz',               'Germany',         50.3569,    7.5890),
    ('Koper Cruise Terminal',              'Koper',                 'Slovenia',        45.5469,   13.7294),
    ('Kristiansand Cruise Terminal',       'Kristiansand',          'Norway',          58.1467,    7.9956),
    ('Kristiansund Cruise Dock',           'Kristiansund',          'Norway',          63.1107,    7.7281),
    ('La Coruna Cruise Terminal',          'La Coruna',             'Spain',           43.3623,   -8.4115),
    ('La Spezia Cruise Terminal',          'La Spezia',             'Italy',           44.1024,    9.8240),
    ('Le Havre Cruise Terminal',           'Le Havre',              'France',          49.4931,    0.1079),
    ('Leixoes Cruise Terminal',            'Porto',                 'Portugal',        41.1853,   -8.7041),
    ('London Tilbury Cruise Terminal',     'London',                'United Kingdom',  51.4564,    0.3613),
    ('Marmaris Cruise Port',               'Marmaris',              'Turkey',          36.8526,   28.2739),
    ('Melk River Cruise Dock',             'Melk',                  'Austria',         48.2297,   15.3317),
    ('Nice Cruise Anchorage',              'Nice',                  'France',          43.7102,    7.2620),
    ('Ponta Delgada Cruise Terminal',      'Ponta Delgada',         'Portugal',        37.7412,  -25.6756),
    ('Portree Cruise Anchorage',           'Portree',               'United Kingdom',  57.4128,   -6.1927),
    ('Prague River Cruise Terminal',       'Prague',                'Czech Republic',  50.0755,   14.4378),
    ('Pula Cruise Terminal',               'Pula',                  'Croatia',         44.8666,   13.8496),
    ('Ravenna Cruise Terminal',            'Ravenna',               'Italy',           44.4184,   12.2035),
    ('Rostock Cruise Terminal',            'Rostock',               'Germany',         54.0887,   12.1403),
    ('Rotterdam Cruise Terminal',          'Rotterdam',             'Netherlands',     51.9225,    4.4792),
    ('Salerno Cruise Terminal',            'Salerno',               'Italy',           40.6824,   14.7681),
    ('Sarande Cruise Dock',                'Sarande',               'Albania',         39.8756,   20.0053),
    ('Savona Cruise Terminal',             'Savona',                'Italy',           44.3049,    8.4773),
    ('Sorrento Cruise Anchorage',          'Sorrento',              'Italy',           40.6264,   14.3758),
    ('Souda Bay Cruise Terminal',          'Souda',                 'Greece',          35.4900,   24.0800),
    ('South Queensferry Cruise Dock',      'South Queensferry',     'United Kingdom',  55.9899,   -3.3947),
    ('St. Peter Port Cruise Anchorage',    'St. Peter Port',        'Guernsey',        49.4551,   -2.5360),
    ('Toulon Cruise Terminal',             'Toulon',                'France',          43.1242,    5.9280),
    ('Vienna River Cruise Terminal',       'Vienna',                'Austria',         48.2082,   16.3738),
    ('Vigo Cruise Terminal',               'Vigo',                  'Spain',           42.2328,   -8.7226),
    ('Villefranche-sur-Mer Anchorage',     'Villefranche-sur-Mer',  'France',          43.7050,    7.3172),

    # Hawaii (additional)
    ('Kailua-Kona Cruise Anchorage',       'Kailua-Kona',           'United States',   19.6400, -155.9969),
    ('Lahaina Cruise Anchorage',           'Lahaina',               'United States',   20.8783, -156.6825),

    # Mexico (additional)
    ('Acapulco Cruise Terminal',           'Acapulco',              'Mexico',          16.8531,  -99.8237),
    ('Huatulco Cruise Port',               'Huatulco',              'Mexico',          15.7597,  -96.1324),
    ('Puerto Chiapas Cruise Terminal',     'Puerto Chiapas',        'Mexico',          14.7236,  -92.4097),

    # Asia / Middle East / Africa (additional)
    ('Ashdod Cruise Terminal',             'Ashdod',                'Israel',          31.8044,   34.6445),
    ('Cairns Cruise Terminal',             'Cairns',                'Australia',      -16.9186,  145.7781),
    ('Chan May Cruise Port',               'Chan May',              'Vietnam',         16.2167,  108.0333),
    ('Cochin Cruise Terminal',             'Kochi',                 'India',            9.9312,   76.2673),
    ('Colombo Cruise Terminal',            'Colombo',               'Sri Lanka',        6.9271,   79.8612),
    ('Eilat Cruise Port',                  'Eilat',                 'Israel',          29.5581,   34.9482),
    ('Fukuoka Cruise Terminal',            'Fukuoka',               'Japan',           33.5904,  130.4017),
    ('Mormugao Cruise Terminal',           'Goa',                   'India',           15.4099,   73.7997),
    ('Ha Long Bay Cruise Dock',            'Ha Long City',          'Vietnam',         20.9101,  107.1839),
    ('Haifa Cruise Terminal',              'Haifa',                 'Israel',          32.8191,   34.9983),
    ('Hobart Cruise Terminal',             'Hobart',                'Australia',      -42.8821,  147.3272),
    ('Isle of Pines Cruise Anchorage',     'Vao',                   'New Caledonia',  -22.6500,  167.4667),
    ('Jeju City Cruise Terminal',          'Jeju City',             'South Korea',     33.4996,  126.5312),
    ('Keelung Cruise Terminal',            'Keelung',               'Taiwan',          25.1276,  121.7392),
    ('Khasab Cruise Port',                 'Khasab',                'Oman',            26.1803,   56.2461),
    ('Ko Samui Cruise Anchorage',          'Ko Samui',              'Thailand',         9.5120,  100.0136),
    ('Manaus Amazon Cruise Terminal',      'Manaus',                'Brazil',          -3.1190,  -60.0217),
    ('Mumbai Cruise Terminal',             'Mumbai',                'India',           18.9388,   72.8354),
    ('Muscat Cruise Terminal',             'Muscat',                'Oman',            23.6139,   58.5922),
    ('Naha Cruise Terminal',               'Naha',                  'Japan',           26.2124,  127.6809),
    ('New Mangalore Cruise Terminal',      'Mangalore',             'India',           12.8698,   74.8428),
    ('Nha Trang Cruise Port',              'Nha Trang',             'Vietnam',         12.2388,  109.1967),
    ('Phu My Cruise Terminal',             'Phu My',                'Vietnam',         10.5614,  107.0386),
    ('Phuket Cruise Terminal',             'Phuket',                'Thailand',         7.8804,   98.3923),
    ('Port Said Cruise Terminal',          'Port Said',             'Egypt',           31.2653,   32.3019),
    ('Safaga Cruise Port',                 'Safaga',                'Egypt',           26.7383,   33.9389),
    ('Sharm El Sheikh Cruise Port',        'Sharm El Sheikh',       'Egypt',           27.9158,   34.3300),
    ('Sihanoukville Cruise Port',          'Sihanoukville',         'Cambodia',        10.6297,  103.5228),
    ('Victoria Seychelles Cruise Terminal','Victoria',              'Seychelles',      -4.6191,   55.4513),

    # Panama Canal / Central America (additional)
    ('Puerto Limon Cruise Terminal',       'Puerto Limon',          'Costa Rica',      10.0036,  -83.0361),
    ('Puerto Quetzal Cruise Terminal',     'Puerto Quetzal',        'Guatemala',       13.9200,  -90.7881),
    ('Puntarenas Cruise Terminal',         'Puntarenas',            'Costa Rica',       9.9764,  -84.8334),
    ('San Juan del Sur Cruise Dock',       'San Juan del Sur',      'Nicaragua',       11.2567,  -85.8739),
    ('Santo Tomas de Castilla Port',       'Santo Tomas de Castilla','Guatemala',      15.6942,  -88.6114),

    # South Pacific (additional)
    ('Airlie Beach Cruise Anchorage',      'Airlie Beach',          'Australia',      -20.2694,  148.7181),
    ('Akaroa Cruise Anchorage',            'Akaroa',                'New Zealand',    -43.8036,  172.9682),
    ('Bay of Islands Cruise Dock',         'Paihia',                'New Zealand',    -35.2800,  174.0897),
    ('Bora Bora Cruise Anchorage',         'Vaitape',               'French Polynesia',-16.5004,-151.7415),
    ('Darwin Cruise Terminal',             'Darwin',                'Australia',      -12.4634,  130.8456),
    ('Kota Kinabalu Cruise Terminal',      'Kota Kinabalu',         'Malaysia',         5.9804,  116.0735),
    ('Kuantan Port',                       'Kuantan',               'Malaysia',         3.7878,  103.3390),
    ('Langkawi Cruise Terminal',           'Langkawi',              'Malaysia',         6.3000,   99.8500),
    ('Lyttelton Cruise Terminal',          'Lyttelton',             'New Zealand',    -43.6031,  172.7264),
    ('Moorea Cruise Anchorage',            'Moorea',                'French Polynesia',-17.5334,-149.8322),
    ('Napier Cruise Terminal',             'Napier',                'New Zealand',    -39.4928,  176.9120),
    ('Papeete Cruise Terminal',            'Papeete',               'French Polynesia',-17.5334,-149.5667),
    ('Penang Cruise Terminal',             'George Town',           'Malaysia',         5.4141,  100.3288),
    ('Picton Cruise Terminal',             'Picton',                'New Zealand',    -41.2952,  174.0039),
    ('Port Chalmers Cruise Terminal',      'Port Chalmers',         'New Zealand',    -45.8188,  170.6269),
    ('Port Denarau Cruise Terminal',       'Nadi',                  'Fiji',            -17.7765,  177.3797),
    ('Port Douglas Cruise Wharf',          'Port Douglas',          'Australia',      -16.4847,  145.4635),
    ('Port Klang Cruise Terminal',         'Port Klang',            'Malaysia',         2.9994,  101.3852),
    ('Port Vila Cruise Terminal',          'Port Vila',             'Vanuatu',         -17.7334,  168.3219),
    ('Suva Cruise Terminal',               'Suva',                  'Fiji',            -18.1248,  178.4501),
    ('Tauranga Cruise Terminal',           'Tauranga',              'New Zealand',    -37.6870,  176.1651),

    # South America (additional)
    ('Arica Cruise Port',                  'Arica',                 'Chile',          -18.4783,  -70.3126),
    ('Callao Cruise Terminal',             'Callao',                'Peru',            -12.0565,  -77.1197),
    ('Coquimbo Cruise Terminal',           'Coquimbo',              'Chile',          -29.9533,  -71.3436),
    ('Puerto Chacabuco Cruise Dock',       'Puerto Chacabuco',      'Chile',          -45.4667,  -72.8333),
    ('Puerto Madryn Cruise Terminal',      'Puerto Madryn',         'Argentina',      -42.7692,  -65.0386),
    ('Puerto Montt Cruise Terminal',       'Puerto Montt',          'Chile',          -41.4693,  -72.9424),
    ('Punta Arenas Cruise Terminal',       'Punta Arenas',          'Chile',          -53.1638,  -70.9171),
    ('Punta del Este Cruise Terminal',     'Punta del Este',        'Uruguay',        -34.9675,  -54.9537),
    ('Salvador de Bahia Cruise Terminal',  'Salvador',              'Brazil',         -12.9714,  -38.5014),
    ('Sullivan Bay Galapagos',             'Sullivan Bay',          'Ecuador',         -0.2000,  -90.6000),
    ('Ushuaia Cruise Terminal',            'Ushuaia',               'Argentina',      -54.8019,  -68.3030),

    # United States (additional)
    ('Newport Cruise Dock',                'Newport',               'United States',   41.4901,  -71.3128),
    ('Catalina Island Cruise Pier',        'Avalon',                'United States',   33.3442, -118.3279),
    ('Port of Astoria',                    'Astoria',               'United States',   46.1879, -123.8313),
    ('Port of Charleston',                 'Charleston',            'United States',   32.7765,  -79.9311),
    ('Santa Barbara Cruise Anchorage',     'Santa Barbara',         'United States',   34.4208, -119.6982),
    ('Victoria Cruise Terminal BC',        'Victoria',              'Canada',          48.4284, -123.3656),
    ('Portland Maine Cruise Terminal',     'Portland',              'United States',   43.6591,  -70.2568),
    ('Key West Cruise Terminal',           'Key West',              'United States',   24.5551,  -81.7800),
]
